name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    runs-on: ${{ matrix.system }}
    permissions:
      contents: read
    strategy:
      matrix:
        system: [x86_64-linux, aarch64-darwin]
    steps:
      - uses: actions/checkout@v4
      - name: om ci
        run: om ci run --extra-access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}" --systems "${{ matrix.system }}"

